---
- name: "Wordpress-Setup"
  hosts: all
  become: true
  tasks:              
          - name: "setting fact values"
            set_fact:
                users: USER_NAME
                db_name: WP_DB_NAME
                db_user: WP_DB_USER
                db_pass: WP_DB_PASSWORD
                domain: DOMAIN_NAME
                mysql_root: MYSQL_ROOT_PASSWORD
                cacheable: true
            tags:
              - mysql_only        

          - name: "Fetching Private IP of WP Server"
            set_fact:
              wp_ip: "{{ ansible_eth0.ipv4.address }}"
            when: inventory_hostname == "WP"

          - name: "Fetching Private IP of DB Server"
            set_fact:
              db_ip: "{{ ansible_eth0.ipv4.address }}"
            when: inventory_hostname == "DB"              

          - include_tasks: wp.yml
            when: inventory_hostname == "WP"
            tags:
              - http_only  
      
          - include_tasks: db.yml
            when: inventory_hostname == "DB"
            tags:
              - mysql_only        
