---
- name: "Wordpress Setup"
  hosts: all
  become: true
  tasks:
          # - include_vars: "./info.yml"
                      
          - name: "setting fact values"
            set_fact:
                users: manu
                db_name: manu-db2
                db_user: manu-user2
                db_pass: manu@1234
                domain: ansible2.devforfree.tech
                mysql_root: root@123
                cacheable: true
            tags:
              - mysql_only        

          - name: "Fetching Private IP of WP Server"
            set_fact:
              wp_ip: "{{ ansible_eth0.ipv4.address }}"
            when: inventory_hostname == "WP"

          - name: "Fetching Private IP of DB Server"
            set_fact:
              db_ip: "{{ ansible_eth0.ipv4.address }}"
            when: inventory_hostname == "DB"              

          - include_tasks: wp.yml
            when: inventory_hostname == "WP"
            tags:
              - http_only  
      
          - include_tasks: db.yml
            when: inventory_hostname == "DB"
            tags:
              - mysql_only        
